package program

import (
	"reference-application/internal/pkg/errorswithcode"
	"reference-application/internal/pkg/id"
)

// ErrInvalidID is error for invalid version identifier.
var ErrInvalidID = errorswithcode.NewValidationErrorWithCode("invalid program id", "INVALID_PROGRAM_ID")

// NewID is a constructor for ID.
// It returns error if version identifier is invalid.
// Example usage:
//
//	newID, err := NewID("00000000-0000-0000-0000-000000000000")
//
// MustNewID same as NewID but panics if version identifier is invalid.
// It could be used in tests or in cases when version identifier will be restored from database.
// Example usage:
//
//	newID := MustNew("00000000-0000-0000-0000-000000000000")
//
// // These functions are generated by id.ConstructorsFactory generic function.
var NewID, MustNewID = id.ConstructorsFactory[*ID](ErrInvalidID)

// ID is a type for id.
type ID struct{ id.Base }
