// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
	"gorm.io/gorm"
	"net"
	http2 "net/http"
	"reference-application/internal/application"
	"reference-application/internal/application/commands/createprogram"
	"reference-application/internal/infrastructure/repositories"
	"reference-application/internal/infrastructure/transports/http"
)

// Injectors from wire.go:

func NewApplication(db *gorm.DB, addr HTTPAddr) Application {
	programRepository := repositories.NewProgramRepository(db)
	handler := createprogram.Handler{
		Repository: programRepository,
	}
	endpoint := createprogram.NewEndpoint(handler)
	endpoints := application.Endpoints{
		CreateProgramEndpoint: endpoint,
	}
	httpHandler := http.NewHandler(endpoints)
	mainApplication := Application{
		HTTPHandler: httpHandler,
		HTTPAddr:    addr,
	}
	return mainApplication
}

// wire.go:

type HTTPAddr string

type Application struct {
	HTTPHandler http2.Handler
	HTTPAddr    HTTPAddr
}

func (app *Application) Run() error {
	ln, err := net.Listen("tcp", string(app.HTTPAddr))
	if err != nil {
		return err
	}
	fmt.Println("HTTP server listening on", string(app.HTTPAddr))
	return app.Serve(ln)
}

func (app *Application) Serve(l net.Listener) error {
	return http2.Serve(l, app.HTTPHandler)
}
